# Question One 
Write a program that will find all numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a list.


In [1]:
Result = []
for i in range(2000,3201):
    if (i%7==0 and i%5!=0):
        Result.append(i)
print(Result)  

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


# Question Two
 Write a program that can compute the factorial of a given number.

In [16]:
# Take an Input 
Input_Number = input("Enter a number : ")
# Calculate Factional
i = int(Input_Number)
Result = 1
while (i>0) :
    Result = Result*i
    i=i-1

print("Fractional is : "+str(Result))

Enter a number : 5
Fractional is : 120


# Question Three
With a given integer number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included).

In [12]:
Input_Number = input("Enter a number : ")
Resulted_Dictionary = {}
for i in range(1,int(Input_Number)+1):
    Resulted_Dictionary[i]=i*i
print ("Output Dictionary is : ")    
print(Resulted_Dictionary)  

Enter a number : 9
Output Dictionary is : 
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}


# Question Four
Given a non-empty string and an int n, return a new string where the char at index n has been removed.

In [11]:
Input_String = input("Enter a string : ")
n = int(input("Enter a number : "))
Output_String = ""
Output_String = ""
for i in range(0,len(Input_String)):
    if(i != n):
        Output_String=Output_String + Input_String[i]
print ("Output Word is : "+Output_String)        

Enter a string : Umbrella
Enter a number : 3
Output Word is : Umbella


# Question Five
Write a NumPy program to convert a NumPy array into a Python list structure.

In [20]:
import numpy as np
Array = np.array([[0,1],[2,3],[4,5]])
LIST=np.zeros(shape=(Array.shape[0],Array.shape[1]),dtype=int)
print ("Original Array")
print(Array)
for i in range(0,len(Array)):
    for j in range(0,len(Array[i])):
      LIST[i,j] = Array[i,j]
print ("Output List")
print(LIST)    

Original Array
[[0 1]
 [2 3]
 [4 5]]
Output List
[[0 1]
 [2 3]
 [4 5]]


# Question Six 
Write a NumPy program to compute the covariance matrix of two given arrays. 


In [2]:
import numpy as np
Variable_1= np.array([0,1,2])
Variable_2= np.array([2,1,0])
#Calculate covariance 
Result=np.cov(Variable_1,Variable_2)
# print Result
print ("Covariance Matrix : ")
print (Result)

Covariance Matrix : 
[[ 1. -1.]
 [-1.  1.]]


# Question Seven
Write a program that calculates and prints the value according to the given formula: Q = Square root of [(2 * C * D)/H] 



In [4]:
import numpy as np
C=50
H=30
# Take an input from the user 
D= input("Enter Comma Separated input  ")
D=D.split(",")
Q=np.zeros(len(D))
for i in range(0,len(D)):
    Q[i]=int(np.floor(np.sqrt(2*C*int(D[i])/H)))
print("The result is : ")
print (Q)    

Enter Comma Separated input  100,150,180
The result is : 
[18. 22. 24.]
